# Generated by Django 4.1.6 on 2023-02-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="image"),
        ),
    ]
