# Generated by Django 4.1.6 on 2023-02-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_ticket_time_created_alter_review_time_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="uploader",
            new_name="user",
        ),
    ]
