# Generated by Django 4.1.6 on 2023-02-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_rename_uploader_ticket_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFollows",
        ),
    ]
