# Generated by Django 4.1.6 on 2023-02-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_ownreview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OwnReview",
        ),
    ]
