# Generated by Django 4.1.6 on 2023-02-21 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_remove_user_following_userfollows"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                related_name="followed_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="UserFollows",
        ),
    ]
